server:
  port: 8080
  servlet:
    context-path: /security
spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sa
    password:
  h2:
    console:
      enabled: true
logging:
  level:
    web: trace
