drop table if exists users cascade;
drop table if exists roles cascade;
drop table if exists users_roles cascade;
create table users (id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
username varchar(50) not null, password varchar(100), email varchar(100));
create table roles (id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY, name varchar(50) not null );
create table users_roles (user_id bigint, role_id bigint, PRIMARY KEY (user_id, role_id));
ALTER TABLE users_roles ADD FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE users_roles ADD FOREIGN KEY (role_id) REFERENCES roles(id);git